-- LensOS beta: run this in Supabase SQL Editor.
-- The browser only uses the publishable/anon key. Never expose a service-role key.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  studio_name text,
  photographer_type text,
  created_at timestamptz not null default now()
);

create table if not exists public.workflow_audits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  survey_answers jsonb not null,
  source text not null default 'lens-os-site',
  created_at timestamptz not null default now()
);

create table if not exists public.consent_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  analytics_opt_in boolean not null default false,
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.workflow_audits enable row level security;
alter table public.consent_preferences enable row level security;

create policy "profiles are private to the owner"
  on public.profiles for select using (auth.uid() = id);
create policy "owners can update their profile"
  on public.profiles for update using (auth.uid() = id);
create policy "owners can create their profile"
  on public.profiles for insert with check (auth.uid() = id);

create policy "audits are private to the owner"
  on public.workflow_audits for select using (auth.uid() = user_id);
create policy "owners can save their audits"
  on public.workflow_audits for insert with check (auth.uid() = user_id);

create policy "consent is private to the owner"
  on public.consent_preferences for select using (auth.uid() = user_id);
create policy "owners can save consent"
  on public.consent_preferences for insert with check (auth.uid() = user_id);
create policy "owners can update consent"
  on public.consent_preferences for update using (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data ->> 'full_name', new.email));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
